### ISSUE TITLE
Obtain input/output in text

### ISSUE THREAD

**Issue by Jamil-Palma** [Azure-Samples/aisearch-openai-rag-audio#34] opened 2024-10-22 12:57 UTC
Hello!
Is it possible to capture both the generated output and input in text as well? Or do I need to implement some additional external resource specifically for this?

My intention is to maintain the current voice functionality, but I also want to have a text record
Regards

**Comment by pamelafox** [comment] 2024-10-22 16:51
See this issue here: https://github.com/Azure-Samples/aisearch-openai-rag-audio/issues/7
There's a fork there with the transcript functionality implemented

**Comment by pamelafox** [comment] 2024-10-25 23:20
Closing this one as a duplicate of #7

**Closed by pamelafox** 2024-10-25 23:20 UTC
